version: 2.1

orbs:
  python: circleci/python@2.1.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: ld4p/ils-middleware
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry

  linting:
    executor: python/default
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Lint with flake8
          command: |
             poetry run flake8
      - run:
          name: Lint with Black
          command: |
             poetry run black --diff --check .

  typechecking:
    executor: python/default
    docker:
      - image: cimg/python:3.11   
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Type check with mypy
          command: |
             poetry run mypy --ignore-missing-imports .

  test:
      executor: python/default
      docker:
        - image: cimg/python:3.11
      steps:
        - checkout
        - python/install-packages:
            pkg-manager: poetry
        - run:
            name: Run tests
            command: |
              poetry run pytest


  publish_to_dockerhub:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker
          command: |
              docker build . -t $IMAGE_NAME:latest
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push $IMAGE_NAME:latest

workflows:
  build:
    jobs:
      - build
      - linting:
          requires:
            - build
      - typechecking:
          requires:
            - build
      - test:
          requires:
            - build
      - publish_to_dockerhub:
          context:
            - ld4p
          filters:
            branches:
              only: main
